# Generated by Django 2.0.5 on 2019-03-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityRecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='post',
            field=models.CharField(choices=[('shuji', '书记'), ('fushuji', '副书记'), ('weiyuan', '委员'), ('putong', '普通党员'), ('qunzhong', '群众')], default='putong', max_length=10, verbose_name='职务'),
        ),
    ]
