# Generated by Django 2.0.5 on 2019-03-22 08:00

import activityRecord.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityRecord', '0002_memberinfo_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='mem_id',
            field=activityRecord.fields.IdField(max_length=6, null=True, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='name',
            field=models.CharField(max_length=16, verbose_name='姓名'),
        ),
    ]
