# Generated by Django 2.0.5 on 2019-04-11 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activityRecord', '0004_auto_20190322_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='allRecorddView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('post', models.CharField(choices=[('shuji', '书记'), ('fushuji', '副书记'), ('weiyuan', '委员'), ('putong', '普通党员'), ('qunzhong', '群众')], max_length=20, verbose_name='职位')),
                ('mem_id', models.CharField(max_length=6, verbose_name='编号')),
                ('actname', models.CharField(max_length=30, verbose_name='活动名称')),
                ('join_time', models.IntegerField(verbose_name='参加次数')),
                ('score', models.IntegerField(verbose_name='单项得分')),
            ],
            options={
                'verbose_name': '单项得分',
                'verbose_name_plural': '单项得分',
                'db_table': 'score_sum_VIEW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='allRecordSumView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('post', models.CharField(choices=[('shuji', '书记'), ('fushuji', '副书记'), ('weiyuan', '委员'), ('putong', '普通党员'), ('qunzhong', '群众')], max_length=20, verbose_name='职位')),
                ('mem_id', models.CharField(max_length=6, verbose_name='编号')),
                ('join_time', models.IntegerField(verbose_name='参加次数')),
                ('score', models.IntegerField(verbose_name='总分')),
            ],
            options={
                'verbose_name': '总分汇总',
                'verbose_name_plural': '总分汇总',
                'db_table': 'all_score_sum_VIEW',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='actinfo',
            name='defaultScore',
            field=models.IntegerField(default='2', verbose_name='负责人电话'),
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='branch',
            field=models.CharField(choices=[('community', '社区党支部'), ('retired', '离退休老干部党支部'), ('company', '非公企业联合党支部')], default='community', max_length=32, verbose_name='所属支部'),
        ),
        migrations.AlterField(
            model_name='actrecord',
            name='score',
            field=models.IntegerField(default=0, verbose_name='活动得分'),
        ),
        migrations.AlterField(
            model_name='actrecord',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 14, 0, 52, 932354, tzinfo=utc), verbose_name='活动时间'),
        ),
    ]
