# Generated by Django 2.0.5 on 2019-04-11 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activityRecord', '0008_auto_20190411_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actrecord',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 15, 28, 57, 973085, tzinfo=utc), verbose_name='活动时间'),
        ),
    ]
