# Generated by Django 2.0.5 on 2019-04-14 01:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activityRecord', '0009_auto_20190411_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='actinfo',
            name='category',
            field=models.CharField(choices=[('changgui', '常规指标'), ('jiafen', '加分项指标'), ('jianfen', '减分项'), ('yipiaofoujue', '一票否决')], default='changgui', max_length=32, verbose_name='指标类别'),
        ),
        migrations.AlterField(
            model_name='actinfo',
            name='defaultScore',
            field=models.IntegerField(default=2, verbose_name='默认分数'),
        ),
        migrations.AlterField(
            model_name='actrecord',
            name='act',
            field=models.ForeignKey(help_text='后缀为该活动默认分数', on_delete=django.db.models.deletion.DO_NOTHING, to='activityRecord.actInfo', verbose_name='活动名称'),
        ),
        migrations.AlterField(
            model_name='actrecord',
            name='score',
            field=models.IntegerField(default=0, help_text='若填0分则记录该活动的默认分数', verbose_name='活动得分'),
        ),
        migrations.AlterField(
            model_name='actrecord',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 1, 30, 8, 296062, tzinfo=utc), verbose_name='活动时间'),
        ),
    ]
